### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/root/google_vm_config.lock'

### ISSUE THREAD

**Issue by wailokkwok** [BaofengZan/GOT-OCRv2-onnx#1]
when I run this to try and convert GOT to onnx

python llm_export.py \
        --path /home/matthew_kwok_tictag_io/gotocr/GOT-OCR2.0/GOT-OCR-2.0-master/GOT_weights \
        --export_split \
        --export_token \
        --export_mnn \
        --onnx_path /home/matthew_kwok_tictag_io/gotocr/GOT-OCR2.0/GOT-OCR-2.0-master/GOT_onnx \
        --mnn_path   /home/matthew_kwok_tictag_io/gotocr/GOT-OCR2.0/GOT-OCR-2.0-master/GOT-mnn
        

this is the error 

Traceback (most recent call last):
  File "/home/matthew_kwok_tictag_io/gotocr/GOT-OCRv2-onnx/llm-export/llm_export.py", line 12, in <module>
    from peft import LoraConfig, TaskType, get_peft_model, PeftModel
  File "/home/matthew_kwok_tictag_io/gotocr/gotocr/lib/python3.10/site-packages/peft/__init__.py", line 22, in <module>
    from .auto import (
  File "/home/matthew_kwok_tictag_io/gotocr/gotocr/lib/python3.10/site-packages/peft/auto.py", line 30, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING
  File "/home/matthew_kwok_tictag_io/gotocr/gotocr/lib/python3.10/site-packages/peft/mapping.py", line 20, in <module>
    from .peft_model import (
  File "/home/matthew_kwok_tictag_io/gotocr/gotocr/lib/python3.10/site-packages/peft/peft_model.py", line 39, in <module>
    from .tuners import (
  File "/home/matthew_kwok_tictag_io/gotocr/gotocr/lib/python3.10/site-packages/peft/tuners/__init__.py", line 21, in <module>
    from .lora import LoraConfig, LoraModel
  File "/home/matthew_kwok_tictag_io/gotocr/gotocr/lib/python3.10/site-packages/peft/tuners/lora.py", line 42, in <module>
    import bitsandbytes as bnb
  File "/home/matthew_kwok_tictag_io/gotocr/gotocr/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/home/matthew_kwok_tictag_io/gotocr/gotocr/lib/python3.10/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/home/matthew_kwok_tictag_io/gotocr/gotocr/lib/python3.10/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/home/matthew_kwok_tictag_io/gotocr/gotocr/lib/python3.10/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/home/matthew_kwok_tictag_io/gotocr/gotocr/lib/python3.10/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/home/matthew_kwok_tictag_io/gotocr/gotocr/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 13, in <module>
    setup.run_cuda_setup()
  File "/home/matthew_kwok_tictag_io/gotocr/gotocr/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 120, in run_cuda_setup
    binary_name, cudart_path, cc, cuda_version_string = evaluate_cuda_setup()
  File "/home/matthew_kwok_tictag_io/gotocr/gotocr/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 337, in evaluate_cuda_setup
    cudart_path = determine_cuda_runtime_lib_path()
  File "/home/matthew_kwok_tictag_io/gotocr/gotocr/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 295, in determine_cuda_runtime_lib_path
    cuda_runtime_libs.update(find_cuda_lib_in(value))
  File "/home/matthew_kwok_tictag_io/gotocr/gotocr/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 232, in find_cuda_lib_in
    resolve_paths_list(paths_list_candidate)
  File "/home/matthew_kwok_tictag_io/gotocr/gotocr/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 227, in resolve_paths_list
    return remove_non_existent_dirs(extract_candidate_paths(paths_list_candidate))
  File "/home/matthew_kwok_tictag_io/gotocr/gotocr/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 201, in remove_non_existent_dirs
    raise exc
  File "/home/matthew_kwok_tictag_io/gotocr/gotocr/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 197, in remove_non_existent_dirs
    if path.exists():
  File "/opt/conda/lib/python3.10/pathlib.py", line 1290, in exists
    self.stat()
  File "/opt/conda/lib/python3.10/pathlib.py", line 1097, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
PermissionError: [Errno 13] Permission denied: '/root/google_vm_config.lock'

**Comment by BaofengZan** [comment]
You need to manually copy  several  json files and  qwen.tiktoken  from the original HF model folder to the folder where ONNX is located.
